### ISSUE TITLE
Convertisseur G-Forming : calcul du courant de base au primaire du transfo

### ISSUE THREAD

**Issue by abruyere** [l2ep-epmlab/Grid-Forming-Models#3]
l semblerait qu'il y ait une coquille dans l'initialisation du masque du modèle de convertisseur avec filtre L : des parenthèses manquantes au niveau du calcul du courant de base au primaire du transfo ; Cf. Image ci-dessous.

![image](https://user-images.githubusercontent.com/37628756/95866238-f8174800-0d67-11eb-82d2-f2b283bae0f9.png)

**Comment by l2ep-epmlab** [comment]
Thanks it has been corrected
